### ISSUE TITLE
it seems doesn't work

### ISSUE THREAD

**Issue by chenghuili** [outeredge/magento-disable-newsletter-email-module#1]
I've disabled all newsletter emails, but they are still sending and got many Bounce and complaints

**Comment by chenghuili** [comment]
<img width="919" alt="Screenshot 2023-10-05 at 14 47 27" src="https://github.com/outeredge/magento-disable-newsletter-email-module/assets/14212956/6470290c-c401-4d1b-a7d9-df42ff926420">
<img width="1349" alt="Screenshot 2023-10-05 at 14 49 36" src="https://github.com/outeredge/magento-disable-newsletter-email-module/assets/14212956/2e8696b3-e43e-42c7-9ae1-1ba6bf954a05">

**Comment by davidwindell** [comment]
Hi @chenghuili 

This module isn't designed to prevent emails from going out, only the Confirmation and Unsubscribe ones.
